# Generated by Django 5.1.1 on 2024-10-02 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bidding_ending_time',
            field=models.TimeField(default=datetime.time(3, 37, 44, 293519)),
        ),
    ]
