# Generated by Django 5.1.1 on 2024-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
    ]
