# Generated by Django 5.1.1 on 2024-10-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='location',
        ),
    ]
