# Generated by Django 5.1.1 on 2024-10-02 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_bidding_ending_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bidding_ending_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 2, 3, 38, 21, 505801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='bidding_ending_time',
            field=models.TimeField(default=datetime.datetime(2024, 10, 2, 3, 38, 21, 505812, tzinfo=datetime.timezone.utc)),
        ),
    ]
