# Generated by Django 5.1.1 on 2024-10-02 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_bidding_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bidding_ending_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='bidding_ending_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
