# Generated by Django 5.1.1 on 2024-11-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_assigned_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='median_auction_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='total_item_returned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
